# Generated by Django 5.1.6 on 2025-04-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='123', max_length=15, unique=True),
        ),
    ]
