# Generated by Django 5.1.6 on 2025-04-15 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dummypayment'),
        ('app', '0004_user_email'),
    ]

    operations = [
    ]
