# Generated by Django 5.1.6 on 2025-04-15 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_merge_0002_dummypayment_0004_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
