# Generated by Django 5.1.6 on 2025-03-19 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.order'),
        ),
    ]
