# Generated by Django 5.1.6 on 2025-03-24 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_cart_cart_user_remove_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
